package io.github.sds100.keymapper.system.permissions

/**
 * Created by sds100 on 08/04/2021.
 */
enum class Permission {
    WRITE_SETTINGS,
    CAMERA,
    DEVICE_ADMIN,
    READ_PHONE_STATE,
    ACCESS_NOTIFICATION_POLICY,
    WRITE_SECURE_SETTINGS,
    NOTIFICATION_LISTENER,
    CALL_PHONE,
    ROOT,
    IGNORE_BATTERY_OPTIMISATION,
    SHIZUKU,
    ACCESS_FINE_LOCATION,
    ANSWER_PHONE_CALL,
    FIND_NEARBY_DEVICES,
}
