files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/strings.xml
  - source: /fastlane/metadata/android/en-US/full_description.txt
    translation: /fastlane/metadata/android/%two_letters_code%/full_description.txt
  - source: /fastlane/metadata/android/en-US/short_description.txt
    translation: /fastlane/metadata/android/%two_letters_code%/short_description.txt
  - source: /fastlane/metadata/android/en-US/title.txt
    translation: /fastlane/metadata/android/%two_letters_code%/title.txt
