package io.github.sds100.keymapper

import androidx.compose.ui.graphics.Color

object ComposeColors {
    val primaryLight = Color(0xFF175DB2)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFD6E3FF)
    val onPrimaryContainerLight = Color(0xFF001B3F)
    val secondaryLight = Color(0xFF005EB5)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFF001B3D)
    val onSecondaryContainerLight = Color(0xFFD4E3FF)
    val tertiaryLight = Color(0xFF0061A3)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFCFE4FF)
    val onTertiaryContainerLight = Color(0xFF001D36)
    val errorLight = Color(0xFFBA1B1B)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD4)
    val onErrorContainerLight = Color(0xFF410001)
    val backgroundLight = Color(0xFFFDFBFF)
    val onBackgroundLight = Color(0xFF1A1B1F)
    val surfaceLight = Color(0xFFFDFBFF)
    val onSurfaceLight = Color(0xFF1A1B1F)
    val surfaceVariantLight = Color(0xFFE0E2EC)
    val onSurfaceVariantLight = Color(0xFF44474F)
    val outlineLight = Color(0xFF74777F)
    val outlineVariantLight = Color(0xFFBFC8CA)
    val inverseSurfaceLight = Color(0xFF2F3034)
    val inverseOnSurfaceLight = Color(0xFFF2F0F4)
    val inversePrimaryLight = Color(0xFFA8C7FF)

    val primaryDark = Color(0xFFA8C7FF)
    val onPrimaryDark = Color(0xFF002F66)
    val primaryContainerDark = Color(0xFF004590)
    val onPrimaryContainerDark = Color(0xFFD6E3FF)
    val secondaryDark = Color(0xFFB1CBD0)
    val onSecondaryDark = Color(0xFF003063)
    val secondaryContainerDark = Color(0xFF00468A)
    val onSecondaryContainerDark = Color(0xFFD4E3FF)
    val tertiaryDark = Color(0xFF9BCAFF)
    val onTertiaryDark = Color(0xFF003259)
    val tertiaryContainerDark = Color(0xFF00497E)
    val onTertiaryContainerDark = Color(0xFFCFE4FF)
    val errorDark = Color(0xFFFFB4A9)
    val onErrorDark = Color(0xFF930006)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD4)
    val backgroundDark = Color(0xFF1A1B1F)
    val onBackgroundDark = Color(0xFFE3E2E6)
    val surfaceDark = Color(0xFF1A1B1F)
    val onSurfaceDark = Color(0xFFE3E2E6)
    val surfaceVariantDark = Color(0xFF44474F)
    val onSurfaceVariantDark = Color(0xFFC4C6CF)
    val outlineDark = Color(0xFF8D9099)
    val outlineVariantDark = Color(0xFF3F484A)
    val inverseSurfaceDark = Color(0xFFE3E2E6)
    val inverseOnSurfaceDark = Color(0xFF1A1B1F)

}