package io.github.sds100.keymapper

/**
 * Created by sds100 on 04/08/2018.
 */
enum class SystemAction {
    //wifi
    ACTION_TOGGLE_WIFI,
    ACTION_ENABLE_WIFI,
    ACTION_DISABLE_WIFI,

    //bluetooth
    ACTION_TOGGLE_BLUETOOTH,
    ACTION_ENABLE_BLUETOOTH,
    ACTION_DISABLE_BLUETOOTH,

    //mobile data
    ACTION_TOGGLE_MOBILE_DATA,
    ACTION_ENABLE_MOBILE_DATA,
    ACTION_DISABLE_MOBILE_DATA,

    //brightness
    ACTION_TOGGLE_AUTO_BRIGHTNESS,

    //auto-rotate
    ACTION_TOGGLE_AUTO_ROTATE,
    ACTION_ENABLE_AUTO_ROTATE,
    ACTION_DISABLE_AUTO_ROTATE,
    ACTION_PORTRAIT_MODE,
    ACTION_LANDSCAPE_MODE
}