# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

sh("bundle install")

default_platform(:android)

desc "Create testing release"
lane :testing do
    gradle(task: "clean assembleFreeCi")
end

desc "Create and deploy production release"
lane :prod do
    version_code = get_properties_value(key: "VERSION_CODE", path: "./app/version.properties")
    version_name = get_properties_value(key: "VERSION_NAME", path: "./app/version.properties")

    whats_new = File.read("../app/src/main/assets/whats-new.txt")
    File.write("metadata/android/en-US/changelogs/" + version_code + ".txt", whats_new)

    gradle(task: "testDebugUnitTest")

    github_token = prompt(
                    text: "Github token: ",
                    secure_text: true
                   )

    ENV["KEYSTORE_PASSWORD"] = prompt(
                    text: "Key store password: ",
                    secure_text: true
                   )

    ENV["KEY_PASSWORD"] = prompt(
                    text: "Key password: ",
                    secure_text: true
                   )

#   Do not release a debug build for pro version.
#   gradle(task: "assembleDebug")
    gradle(task: "assembleProRelease")
    gradle(task: "bundleProRelease")

    apk_path_release="app/build/outputs/apk/pro/release/keymapper-" + version_name + ".apk"

    github_release = set_github_release(
      repository_name: "keymapperorg/KeyMapper",
      api_bearer: github_token,
      name: version_name,
      tag_name: "v" + version_name,
      description: whats_new,
      commitish: "master",
      upload_assets: [apk_path_release],
      is_draft: false,
      is_prerelease: false
    )

    supply(
        aab: "app/build/outputs/bundle/proRelease/app-pro-release.aab",
        track: "beta",
        release_status: "draft",
        skip_upload_apk: true
    )
end
