package io.github.sds100.keymapper.base.constraints

import kotlinx.serialization.Serializable

// THESE MUST BE ORDERED IN HOW THE CONSTRAINTS SHOULD BE SORTED
// IN THE KEY MAP LIST
@Serializable
enum class ConstraintId {
    APP_IN_FOREGROUND,
    APP_PLAYING_MEDIA,
    MEDIA_PLAYING,

    BT_DEVICE_CONNECTED,

    SCREEN_ON,

    DISPLAY_ORIENTATION_PORTRAIT,
    DISPLAY_ORIENTATION_LANDSCAPE,
    DISPLAY_ORIENTATION_0,
    DISPLAY_ORIENTATION_90,
    DISPLAY_ORIENTATION_180,
    DISPLAY_ORIENTATION_270,

    PHYSICAL_ORIENTATION_PORTRAIT,
    PHYSICAL_ORIENTATION_LANDSCAPE,
    PHYSICAL_ORIENTATION_PORTRAIT_INVERTED,
    PHYSICAL_ORIENTATION_LANDSCAPE_INVERTED,

    DISPLAY_RESOLUTION,

    FLASHLIGHT_ON,

    WIFI_ON,
    WIFI_CONNECTED,

    IME_CHOSEN,

    KEYBOARD_SHOWING,

    DEVICE_IS_LOCKED,
    LOCK_SCREEN_SHOWING,

    IN_PHONE_CALL,
    NOT_IN_PHONE_CALL,
    PHONE_RINGING,

    RINGER_MODE_NORMAL,
    RINGER_MODE_VIBRATE,
    RINGER_MODE_SILENT,

    CHARGING,

    HINGE_CLOSED,
    HINGE_OPEN,

    NOTIFICATION_PANEL_SHOWING,

    TIME,
}
